Feature/auth
AssetOtinchiev/crypto-bank-monolith pull request #1
Opened 2023-05-28 16:18 UTC by AssetOtinchiev

Added Account logic

  1. Create an account
  2. Get the list of accounts
  3. Get report count  by period(only for analyst user)

Added Auth logic 

  1. Auth (logic password)

Added User logic

1. Get a User Profile
2. Update user roles
3. Get user roles
4. Create a User

2023-05-30 03:47 UTC, mitro requested changes

2023-05-30 03:47 UTC, mitro commented on WebApi/Features/Auth/Services/TokenService.cs
>          var userRecord = await _dbContext.Users
Тут не нужно проверять, существует ли пользователь. Инвариант этого метода заключается в том, что `user`, переданный в качестве аргумента, не равен `null`. Предлагаю явно описать этот вариант через строку `ArgumentNullException.ThrowIfNull(user);` в начале метода. И стараться так описывать инварианты и в других местах

2023-05-30 03:47 UTC, mitro commented on WebApi/Features/Auth/Services/TokenService.cs
> +        //var salt = PasswordHelper.GetSecureSalt();
Предлагаю удалить закомментированный код - лишнее отвлечение. Если нужно, можно будет в git найти

2023-05-30 03:47 UTC, mitro commented on WebApi/Features/Auth/Services/TokenService.cs
> +    public async Task<Tuple<string, string>> GenerateTokensAsync(User user, CancellationToken cancellationToken)
Можно вместо `Tuple` использовать просто `Task<(string, string)>`. И в конце метода тоже поправить

2023-05-30 03:47 UTC, mitro commented on WebApi/Features/Users/Domain/User.cs
> +    public DateTime DateOfRegistration { get; set; } = DateTime.Now.ToUniversalTime();
Лучше не использовать тут значение по умолчанию, а заполнять свойство в хендлере регистрации. Так будет более явно. Тем более объект типа `User` создается и для уже существующих пользователей и там это значение не будет иметь смысла. Оно будет просто сразу перезаписано. И это в лучшем случае. А в худшем, останется дефолтное значение и приведёт к изменению даты регистрации

2023-05-30 03:47 UTC, mitro commented on WebApi/Features/Users/Models/UserModel.cs
> +    public DateTime DateOfRegistration { get; set; } = DateTime.Now.ToUniversalTime();
Стоит убрать дефолтное значение. Описал причину в файле User.cs

2023-05-30 03:47 UTC, mitro commented on WebApi/Features/Auth/Requests/Authenticate.cs
>              var refreshTokenModel = new RefreshTokenModel
С классом `RefreshTokenModel` есть несколько проблем:

1. В названии фигурирует только refresh token, хотя внутри есть и access token
2. Нет смысла возвращать `Id` и `Email`. Если они нужны на фронте, то их всегда можно достать из JWT
3. Я забыл рассказать про это на занятии, но refresh token лучше возвращать в виде HttpOnly cookie. И в этом cookie установить Path, чтобы она слалась только на эндпоинт рефреша токена. В таком случае JS код на фронте не будет иметь доступа к рефреш токену, что повышает безопасность https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies

С учетом всего этого предлагаю в классе `RefreshTokenModel` оставить только свойство `AccessToken` плюс переименовать его в `AccessTokenModel`. Из хендлера возвращать access token и refresh token просто в `Response`. И уже в контроллере просаживать refresh token в cookie, а access token в модельку

2023-05-30 03:47 UTC, mitro commented on WebApi/Features/Auth/Registration/AuthBuilderExtension.cs
> +                ValidateIssuerSigningKey = true,
Нужно еще включить `ValidateLifetime`

2023-05-30 03:47 UTC, mitro commented on WebApi/Features/Users/Requests/RegisterUser.cs
>              RuleFor(x => x.RegisterUserModel.Email).MustAsync(async (x, token) =>
А что если нам `CascadeMode` включать в конкретном `RuleFor`, а не на уровне класса? Но для этого правила валидации Email нужно будет объединить в один вызов. И тогда, если Email пустой, то его поиск в БД производиться не будет. Но другие правила (для Password и DateOfBirth) будут выполняться и клиент получит респонс со всеми ошибками. Я предполагаю, что это так будет работать, но не проверял. Проверишь?

2023-05-30 03:47 UTC, mitro commented on WebApi/Features/Users/Requests/EditUserRoles.cs
> +                .ToArrayAsync(cancellationToken: cancellationToken);
Название параметра можно не использовать

2023-05-30 03:47 UTC, mitro commented on WebApi/Features/Users/Requests/Controllers/UserController.cs
> +        var response = await _dispatcher.Dispatch(new GetUserProfile.Request(userId), cancellationToken);
`Dispatcher` использовать необязательно. Я его создал, чтобы продемонстировать, что можно абстрагировать Mediatr и при необходимости поменять на другую реализацию. Но в реальной жизни можно смело просто `IMediator` использовать. В случае с контроллерами скоуп DI будет создаваться. В общем, тут тебе решать, нужна эта абстракция или нет

2023-05-30 03:47 UTC, mitro commented on WebApi/Features/Users/Requests/Controllers/UserController.cs
> +    public async Task<UserModel> GetUserProfile(Guid userId, CancellationToken cancellationToken)
Нужно закрыть эту операцию авторизацией и брать `userId` из `User`, созданного из JWT

2023-05-30 03:47 UTC, mitro commented on WebApi/Features/Users/Requests/Controllers/UserController.cs
> +    [Authorize(Roles = nameof(RoleType.Administrator))]
Это из коробки работает? Authentication Middleware понимает, что нужно заполнить роли пользователя из клейма "roles" в JWT?

2023-05-30 03:47 UTC, mitro commented on WebApi/Shared/PasswordHelper.cs
> +       var argon2 = new Argon2id(Encoding.UTF8.GetBytes(password));
Предлагаю пароль и соль хранить в одной строке в БД. И, кроме этого, хранить там также параметры алгоритма. Посмотри, как это тут реализовано https://argon2.online/

В таком случае мы сможем на протяжении жизни системы менять параметры алгоритма при необходимости, чтобы повысить безопасность. Чтобы проверить хеш при логине мы просто считываем параметры из строки. А текущие параметры давай вынесем в конфиг.

И в дополнение это даст нам возможность перехешировать пароли на логине. При логине мы можем смотреть на параметры в строке и сравнивать их с теми, что сейчас в конфиге. Если они различаются, мы перехешируем пароль и обновляем его в БД.

2023-05-30 03:48 UTC, mitro commented
Предлагаю удалить старые проекты, чтобы не болтались под ногами

2023-05-30 04:24 UTC, AssetOtinchiev commented on WebApi/Database/AppDbContext.cs
> +                .HasConstraintName("FK_Accounts_User");
тут да согласен

2023-05-30 04:26 UTC, AssetOtinchiev commented on WebApi/Features/Users/Requests/EditUserRoles.cs
> +                .ToArrayAsync(cancellationToken: cancellationToken);
тут немного не понял , вы про userRoles или request.UserId  @mitro ?

2023-05-30 04:27 UTC, AssetOtinchiev commented on WebApi/Features/Users/Requests/Controllers/UserController.cs
> +        var response = await _dispatcher.Dispatch(new GetUserProfile.Request(userId), cancellationToken);
я все же думаю буду использовать `Dispatcher` так как идею с логированием времени запросов интересна

2023-05-30 04:28 UTC, AssetOtinchiev commented on WebApi/Features/Users/Requests/Controllers/UserController.cs
> +        var response = await _dispatcher.Dispatch(new GetUserProfile.Request(userId), cancellationToken);
Если в будущем ничего к dispatcher не добавится то уберу его

2023-05-30 04:29 UTC, AssetOtinchiev commented on WebApi/Features/Users/Requests/Controllers/UserController.cs
> +    [Authorize(Roles = nameof(RoleType.Administrator))]
Да я проверял , все работает , я на другом проекте с identity использовал такой подход

2023-05-30 04:32 UTC, AssetOtinchiev commented on WebApi/Features/Users/Requests/Controllers/UserController.cs
> +    public async Task<UserModel> GetUserProfile(Guid userId, CancellationToken cancellationToken)
да я как раз ниже закомментил  доставание из jwt)

2023-05-30 05:25 UTC, AssetOtinchiev commented on WebApi/Shared/PasswordHelper.cs
> +       var argon2 = new Argon2id(Encoding.UTF8.GetBytes(password));
<img width="1150" alt="Screenshot 2023-05-30 at 11 24 17" src="https://github.com/AssetOtinchiev/crypto-bank-monolith/assets/40349309/04a2f703-4c57-464f-929b-58716bae151a">
Вы про эту строку?

2023-05-30 05:26 UTC, AssetOtinchiev commented on WebApi/Shared/PasswordHelper.cs
> +       var argon2 = new Argon2id(Encoding.UTF8.GetBytes(password));
Хранить сам Encoded form в базе?

2023-05-30 05:33 UTC, AssetOtinchiev commented on WebApi/Shared/PasswordHelper.cs
> +       var argon2 = new Argon2id(Encoding.UTF8.GetBytes(password));
И конфиг такой будет?
"PasswordValidator":{
    "Type": "argon2i",
    "Salt": "f1nd1ngn3m0"
  },

2023-05-30 07:42 UTC, mitro commented on WebApi/Features/Users/Requests/EditUserRoles.cs
> +                .ToArrayAsync(cancellationToken: cancellationToken);
Вместо `.ToArrayAsync(cancellationToken: cancellationToken)` можно использовать просто `.ToArrayAsync(cancellationToken)`

2023-05-30 07:43 UTC, mitro commented on WebApi/Features/Users/Requests/Controllers/UserController.cs
> +        var response = await _dispatcher.Dispatch(new GetUserProfile.Request(userId), cancellationToken);
Хорошо, понял. Но логгирование запросов никак не зависит от `Dispatcher`. Оно реализуется с помощью MediatR Behaviors

2023-05-30 07:44 UTC, mitro commented on WebApi/Shared/PasswordHelper.cs
> +       var argon2 = new Argon2id(Encoding.UTF8.GetBytes(password));
Да, я про эту строку. В таком виде нужно хранить в БД: Алгоритм, параметры, соль, хеш пароля - всё разделенное символом `$`

2023-05-30 07:46 UTC, AssetOtinchiev commented on WebApi/Shared/PasswordHelper.cs
> +       var argon2 = new Argon2id(Encoding.UTF8.GetBytes(password));
Все понял)

2023-05-30 15:44 UTC, AssetOtinchiev commented on WebApi/Features/Accounts/Requests/CreateAccount.cs
> +    public record Request(CreateAccountModel CreateAccountModel) : IRequest<Response>;
да я после вашего урока увидел что можно просто прописывать параметры прям в request, и что в контроллере тоже принимать CreateAccount.Request request, просто мало опыта с Mediatr

2023-05-30 16:10 UTC, AssetOtinchiev commented on WebApi/Features/Users/Requests/RegisterUser.cs
> +            var isExistAdmin = await _dbContext.Roles.AnyAsync(x => x.Name == RoleType.Administrator, cancellationToken: cancellationToken);
у меня райдер автоматом создает их)

2023-05-30 16:22 UTC, AssetOtinchiev commented on WebApi/Features/Auth/Requests/Authenticate.cs
>              var refreshTokenModel = new RefreshTokenModel
я пока функционал с Refresh token отложу в новую ветку, буду пока возвращать  AccessToken

2023-05-30 16:58 UTC, AssetOtinchiev commented on WebApi/Features/Auth/Requests/Authenticate.cs
>              {
Переделал примерно так , не уверен что валидно
```
 public async Task<Response> Handle(Request request, CancellationToken cancellationToken)
        {
            var user = _dbContext.Users
                .Include(x=> x.Roles)
                .SingleOrDefault(user => user.Email == request.RegisterUserModel.Email);

            if (user == null)
            {
                throw new ValidationErrorsException($"{nameof(request.RegisterUserModel.Email)}", "Invalid credentials","");
            }
```

2023-05-30 17:29 UTC, AssetOtinchiev commented on WebApi/Features/Users/Requests/RegisterUser.cs
>              RuleFor(x => x.RegisterUserModel.Email).MustAsync(async (x, token) =>
Попробовал `.Cascade(CascadeMode.Stop)` , но он все равно в базу зашел
<img width="763" alt="image" src="https://github.com/AssetOtinchiev/crypto-bank-monolith/assets/40349309/de6728e3-63f4-42cc-8ed2-29afcb36b010">

2023-05-31 04:46 UTC, AssetOtinchiev commented on WebApi/Features/Users/Requests/RegisterUser.cs
>              RuleFor(x => x.RegisterUserModel.Email).MustAsync(async (x, token) =>
fixed

2023-06-01 07:27 UTC, merged